# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-04 14:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_facebookuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facebookuser',
            name='user_password',
            field=models.BinaryField(),
        ),
    ]
