# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-05 06:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cms', '0004_auto_20170304_1455'),
    ]

    operations = [
        migrations.CreateModel(
            name='Otp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp_umber', models.IntegerField(default=0)),
                ('user_name', models.CharField(max_length=1000)),
                ('user_email', models.CharField(max_length=1000)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('video', models.FileField(upload_to='videos')),
                ('cuisine_type', models.CharField(choices=[('Indian', 'Indian'), ('Japnese', 'Japnese'), ('Chinese', 'Chinese'), ('Mexican', 'Mexican'), ('American', 'American'), ('Italian', 'Italian'), ('French', 'French'), ('Asian', 'Asian'), ('Others', 'Others')], max_length=1000)),
                ('recipe', models.CharField(max_length=1000)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
